namespace Dodkin
{
    /// <summary>The properties to read when receiving a message</summary>
    [Flags]
    public enum MessageProperty : ulong
    {
        None                = 0ul,
        Class               = 1ul << 0,
        MessageId           = 1ul << 1,
        CorrelationId       = 1ul << 2,
        Priority            = 1ul << 3,
        Delivery            = 1ul << 4,
        Acknowledge         = 1ul << 5,
        Journal             = 1ul << 6,
        AppSpecific         = 1ul << 7,
        Body                = 1ul << 8,
        Label               = 1ul << 9,
        TimeToReachQueue    = 1ul << 10,
        TimeToBeReceived    = 1ul << 11,
        RespQueue           = 1ul << 12,
        AdminQueue          = 1ul << 13,
        Version             = 1ul << 14,
        SenderId            = 1ul << 15,
        SenderIdType        = 1ul << 16,
        PrivLevel           = 1ul << 17,
        AuthLevel           = 1ul << 18,
        Authenticated       = 1ul << 19,
        HashAlg             = 1ul << 20,
        EncryptionAlg       = 1ul << 21,
        SenderCert          = 1ul << 22,
        SrcMachineId        = 1ul << 23,
        SentTime            = 1ul << 24,
        ArrivedTime         = 1ul << 25,
        DestQueue           = 1ul << 26,
        Extension           = 1ul << 27,
        SecurityContext     = 1ul << 28,
        ConnectorType       = 1ul << 29,
        XactStatusQueue     = 1ul << 30,
        Trace               = 1ul << 31,
        BodyType            = 1ul << 32,
        DestSymmKey         = 1ul << 33,
        Signature           = 1ul << 34,
        ProvType            = 1ul << 35,
        ProvName            = 1ul << 36,
        FirstInXact         = 1ul << 37,
        LastInXact          = 1ul << 38,
        XactId              = 1ul << 39,
        AuthenticatedEx     = 1ul << 40,
        RespFormatName      = 1ul << 41,
        DestFormatName      = 1ul << 42,
        LookupId            = 1ul << 43,
        SoapEnvelope        = 1ul << 44,
        CompoundMessage     = 1ul << 45,
        SoapHeader          = 1ul << 46,
        SoapBody            = 1ul << 47,
        DeadLetterQueue     = 1ul << 48,
        AbortCount          = 1ul << 49,
        MoveCount           = 1ul << 50,
        LastMoveTime        = 1ul << 51,
        //todo: change to all properties that can be received together
        All                 = 0xFFFF_FFFF_FFFF_FFFF,
    }
}