<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Dodkin.Dispatch</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Dodkin Dispatch</Title>
    <Description>Message dispatcher powered by Relay Toolkit and Unix domain sockets</Description>
    <PackageId>Dodkin.Dispatch.Uds</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/vborovikov/dodkin</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vborovikov/dodkin.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>uds;ipc;cqrs</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dodkin.Tests" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <Compile Include="..\Dodkin.Dispatch.Msmq\EventIds.cs" Link="EventIds.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dodkin.Dispatch" Version="0.7.0-beta.1" Condition="'$(Configuration)'=='Release'" />
    <ProjectReference Include="..\Dodkin.Dispatch\Dodkin.Dispatch.csproj" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
  </ItemGroup>

</Project>
